<?php

namespace Tests;

use \Core\ServiceLocator;
use \Core\LogService;
use \PHPUnit\Framework\TestCase;

class ServiceLocatorTest extends TestCase
{
    /**
     * @var ServiceLocator
     */
    private $serviceLocator;

    public function setUp()
    {
        $this->serviceLocator = new ServiceLocator();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLocator()
    {
        $this->serviceLocator->set(LogService::class, function ()  {
            return new LogService();
        });
        $this->assertTrue($this->serviceLocator->has(LogService::class));
        $this->assertFalse($this->serviceLocator->has(self::class));
    }
}
